2025-04-08 22:30:16,093 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n_gcp/query.py", line 209, in resources
    resources = self._fetch_resources(q)
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n_gcp/query.py", line 231, in _fetch_resources
    return self.augment(self.source.get_resources(query)) or []
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n_gcp/query.py", line 76, in get_resources
    return self.query.filter(self.manager, **query)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n_gcp/query.py", line 35, in filter
    project = session.get_default_project()
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n_gcp/client.py", line 227, in get_default_project
    raise ValueError("No GCP Project ID set - set CLOUDSDK_CORE_PROJECT")
ValueError: No GCP Project ID set - set CLOUDSDK_CORE_PROJECT
