2025-04-09 13:33:05,778 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n_gcp/query.py", line 215, in resources
    resources = self.filter_resources(resources)
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n/manager.py", line 113, in filter_resources
    resources = f.process(resources, event)
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n_gcp/filters/metrics.py", line 123, in process
    project = session.get_default_project()
  File "/Users/gurukallam/projects/finops360/cloud-custodian-policies/venv/lib/python3.13/site-packages/c7n_gcp/client.py", line 227, in get_default_project
    raise ValueError("No GCP Project ID set - set CLOUDSDK_CORE_PROJECT")
ValueError: No GCP Project ID set - set CLOUDSDK_CORE_PROJECT
